version: '3'
services:
    nginx:
        image: nginx:1.13
        container_name: nginx
        volumes:
            - ./app/:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8083:80"
        depends_on:
            - php
        networks:
            - traefik-net

    php:
        build: ./php
        container_name: php
        working_dir: /var/www/html
        ports:
            - "9000:9000"
        volumes:
            - ./app/:/var/www/html
        networks:
           - traefik-net

networks:
    traefik-net: